package dev.daisycloud.provider.minecraft;

import dev.daisycloud.provider.spi.ProviderLifecycleCapabilities;
import dev.daisycloud.provider.spi.ProviderOperationKind;
import dev.daisycloud.provider.spi.ProviderRegistration;
import dev.daisycloud.provider.spi.ResourceTypeRegistration;

import java.util.List;

public final class MinecraftServerProviderCatalog {
    public static final String PROVIDER_ID = "DaisyCloud.Minecraft";
    public static final String SERVER_RESOURCE_TYPE = "servers";

    private MinecraftServerProviderCatalog() {
    }

    public static ProviderRegistration registration() {
        return new ProviderRegistration(
                PROVIDER_ID,
                "Minecraft Server Hosting",
                List.of(new ResourceTypeRegistration(
                        SERVER_RESOURCE_TYPE,
                        "Minecraft Servers",
                        lifecycleCapabilities())));
    }

    private static ProviderLifecycleCapabilities lifecycleCapabilities() {
        return new ProviderLifecycleCapabilities(
                List.of(ProviderOperationKind.values()),
                List.of(
                        "resourceId",
                        "desiredProperties",
                        "observedState",
                        "diagnostics",
                        "serverName",
                        "edition",
                        "minecraftVersion",
                        "serverType",
                        "containerRuntime",
                        "serverImage",
                        "memoryMb",
                        "vcpu",
                        "storageGb",
                        "region",
                        "adminPanel",
                        "panelAccess",
                        "adminPanelState",
                        "adminPanelRoutes",
                        "adminPanelPermissionTiers",
                        "adminPanelAuditEvents",
                        "adminPanelSecurityPolicy",
                        "adminPanelSupportBundle",
                        "adminPanelUxSchema",
                        "adminPanelRealtimeChannels",
                        "adminPanelFileTools",
                        "adminPanelConfigTools",
                        "adminPanelPlayerTools",
                        "adminPanelWorldTools",
                        "adminPanelDatabaseTables",
                        "adminPanelWorkflowEvidence",
                        "selectedMods",
                        "selectedPlugins",
                        "modpackId",
                        "marketplaceSchema",
                        "marketplaceMode",
                        "marketplaceSources",
                        "marketplaceSearchEndpoints",
                        "marketplaceDependencyStrategy",
                        "marketplaceInstallPolicy",
                        "marketplaceMalwareScan",
                        "marketplaceRollbackPolicy",
                        "marketplaceInstallPlan",
                        "marketplaceDatabaseTables",
                        "marketplaceEvidence",
                        "databaseMode",
                        "databaseProvider",
                        "databaseResourceType",
                        "databaseResourceId",
                        "databaseName",
                        "databaseEndpoint",
                        "databaseSku",
                        "databaseSchemaVersion",
                        "databaseTables",
                        "databaseBootstrapSql",
                        "databaseEvidence",
                        "instanceManagerSchema",
                        "instanceManagerState",
                        "activeInstance",
                        "maxInstances",
                        "instanceSlots",
                        "instanceSwitchPolicy",
                        "instanceDatabaseTables",
                        "instanceEvidence",
                        "backupPolicy",
                        "backupPolicySchema",
                        "backupScope",
                        "backupStorage",
                        "backupCompression",
                        "backupBeforeDestructiveChanges",
                        "backupRecoveryPointObjective",
                        "backupOffsitePolicy",
                        "networkMode",
                        "networkPolicySchema",
                        "networkExposure",
                        "networkGameEndpoint",
                        "networkPanelEndpoint",
                        "networkFirewallRules",
                        "networkDaisyNetworkBinding",
                        "networkDdosPolicy",
                        "networkTlsMode",
                        "gamemode",
                        "difficulty",
                        "viewDistance",
                        "simulationDistance",
                        "motd",
                        "containerManifestVersion",
                        "containerServiceName",
                        "containerResourceLimits",
                        "containerRestartPolicy",
                        "startupFileNames",
                        "nodeAgentTaskSchema",
                        "nodeAgentTaskId",
                        "nodeAgentAction",
                        "nodeAgentIdempotencyKey",
                        "nodeAgentReconcileDigest",
                        "nodeAgentExecutionPlan",
                        "importMode",
                        "importScope",
                        "exportFormat",
                        "exportScope",
                        "contentLockSchema",
                        "contentLockDigest",
                        "contentLockItemCount",
                        "contentResolverMode",
                        "contentLockWarningCount",
                        "contentWarnings"),
                List.of(
                        "validate",
                        "plan",
                        "apply",
                        "observe",
                        "backup",
                        "restore",
                        "backup-policy",
                        "restore-policy",
                        "diagnose",
                        "import-state",
                        "export-state",
                        "console",
                        "logs",
                        "tps",
                        "players",
                        "mod-resolution",
                        "network-policy",
                        "firewall-policy",
                        "ddos-policy",
                        "route-binding",
                        "container-manifest",
                        "startup-files",
                        "node-agent-handoff",
                        "node-agent-idempotency",
                        "admin-panel-routes",
                        "admin-panel-permissions",
                        "admin-panel-audit",
                        "content-lock",
                        "content-resolution",
                        "live-marketplace-contract",
                        "marketplace-dependency-resolution",
                        "marketplace-malware-scan-policy",
                        "marketplace-rollback-policy",
                        "daisybase-control-plane",
                        "database-bootstrap-sql",
                        "instance-manager",
                        "instance-switching",
                        "admin-panel-realtime",
                        "admin-panel-file-editor",
                        "admin-panel-player-actions",
                        "admin-panel-world-manager"),
                List.of(
                        "registration",
                        "validate-plan-conformance",
                        "lifecycle-operation-conformance",
                        "minecraft-server-container-plan",
                        "minecraft-container-manifest",
                        "minecraft-startup-files",
                        "minecraft-node-agent-task",
                        "minecraft-node-agent-idempotency",
                        "minecraft-admin-panel-profile",
                        "minecraft-network-policy-profile",
                        "minecraft-backup-policy-profile",
                        "minecraft-daisybase-profile",
                        "minecraft-live-marketplace-profile",
                        "minecraft-instance-manager-profile",
                        "minecraft-admin-ux-profile",
                        "minecraft-import-export-contract",
                        "minecraft-content-lock",
                        "minecraft-offline-content-resolution",
                        "admin-panel-policy",
                        "mod-selection-compatibility"));
    }
}
